# Generated by Django 3.2.4 on 2021-06-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.TextField(max_length=30)),
                ('dono_loja', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tranzacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
                ('hora', models.TimeField()),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('cpf', models.TextField()),
                ('cartao', models.TextField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_loja.loja')),
            ],
        ),
    ]
