# Generated by Django 3.2.4 on 2021-06-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0002_alter_tranzacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzacao',
            name='tipo',
            field=models.CharField(max_length=1),
        ),
    ]
