# Generated by Django 3.2.4 on 2021-06-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0003_alter_tranzacao_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tranzacao',
            options={'ordering': ['data', 'hora']},
        ),
        migrations.AlterField(
            model_name='tranzacao',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
