# Generated by Django 3.2.4 on 2021-06-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0004_auto_20210620_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
